/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nanoware.view;

import com.nanoware.bll.Functions;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author Mothusi Molorane
 */
public class MenuFinance extends javax.swing.JFrame {
    

    /**
     * Creates new form MenuFinance
     */
    public MenuFinance() {
        initComponents();
        
        Functions.setAppIcon(MenuFinance.this);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtbtnTimetable = new javax.swing.JToggleButton();
        jtbtnApplications = new javax.swing.JToggleButton();
        jtbtnSettings = new javax.swing.JToggleButton();
        jtbtnUsers = new javax.swing.JToggleButton();
        jtbtnAttendance = new javax.swing.JToggleButton();
        jtbtnAdmissions2 = new javax.swing.JToggleButton();
        jtbtnStaff = new javax.swing.JToggleButton();
        jtbtnEnrolments = new javax.swing.JToggleButton();
        jtbtnAdmissions = new javax.swing.JToggleButton();
        jtbtnAccounts = new javax.swing.JToggleButton();
        jtbtnAdmissions6 = new javax.swing.JToggleButton();
        jtbtnAdmissions7 = new javax.swing.JToggleButton();
        jtbtnAdmissions8 = new javax.swing.JToggleButton();
        jtbtnAdmissions9 = new javax.swing.JToggleButton();
        jtbtnCampuses = new javax.swing.JToggleButton();
        jtbtnAdmissions11 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(Functions.pnlBackgroundBottom());
        jPanel3.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(Functions.designedDetails());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(Functions.pnlBackgroundTop());
        jPanel4.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("FINANCE PANEL");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("THE STUDENT PORTAL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jtbtnTimetable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnTimetable.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/clock.png"))); // NOI18N
        jtbtnTimetable.setText("Time Table");
        jtbtnTimetable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnTimetable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnApplications.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnApplications.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnApplications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/application.png"))); // NOI18N
        jtbtnApplications.setText("Applications");
        jtbtnApplications.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnApplications.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnApplicationsActionPerformed(evt);
            }
        });

        jtbtnSettings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnSettings.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/settings1.png"))); // NOI18N
        jtbtnSettings.setText("Settings");
        jtbtnSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnSettingsActionPerformed(evt);
            }
        });

        jtbtnUsers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnUsers.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/account.png"))); // NOI18N
        jtbtnUsers.setText("Users");
        jtbtnUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnAttendance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAttendance.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/attendance.png"))); // NOI18N
        jtbtnAttendance.setText("Attendance");
        jtbtnAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAttendance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAttendanceActionPerformed(evt);
            }
        });

        jtbtnAdmissions2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions2.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/bank.png"))); // NOI18N
        jtbtnAdmissions2.setText("Sponsors");
        jtbtnAdmissions2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnStaff.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnStaff.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/service.png"))); // NOI18N
        jtbtnStaff.setText("Staff");
        jtbtnStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnStaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnEnrolments.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnEnrolments.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnEnrolments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/clipboard.png"))); // NOI18N
        jtbtnEnrolments.setText("Enrolments");
        jtbtnEnrolments.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnEnrolments.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnEnrolments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnEnrolmentsActionPerformed(evt);
            }
        });

        jtbtnAdmissions.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/icon2.png"))); // NOI18N
        jtbtnAdmissions.setText("Admissions");
        jtbtnAdmissions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnAdmissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAdmissionsActionPerformed(evt);
            }
        });

        jtbtnAccounts.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAccounts.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAccounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/shopping-cart.png"))); // NOI18N
        jtbtnAccounts.setText("Accounts");
        jtbtnAccounts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAccounts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAccountsActionPerformed(evt);
            }
        });

        jtbtnAdmissions6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions6.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/law1.png"))); // NOI18N
        jtbtnAdmissions6.setText("Assessments");
        jtbtnAdmissions6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnAdmissions7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions7.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/test.png"))); // NOI18N
        jtbtnAdmissions7.setText("Tests");
        jtbtnAdmissions7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnAdmissions8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions8.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/pass1.png"))); // NOI18N
        jtbtnAdmissions8.setText("Exams");
        jtbtnAdmissions8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnAdmissions9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions9.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/speaker.png"))); // NOI18N
        jtbtnAdmissions9.setText("Lecture");
        jtbtnAdmissions9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnCampuses.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnCampuses.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnCampuses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/campus.png"))); // NOI18N
        jtbtnCampuses.setText("Campuses");
        jtbtnCampuses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnCampuses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnAdmissions11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions11.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard/analytics4.png"))); // NOI18N
        jtbtnAdmissions11.setText("Results");
        jtbtnAdmissions11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtbtnAdmissions2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnAdmissions9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnAdmissions7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnEnrolments, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbtnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnAdmissions, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jtbtnApplications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbtnCampuses, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jtbtnAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbtnAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnAdmissions8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnAdmissions6, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbtnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnTimetable, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnAdmissions11, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbtnEnrolments, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnAdmissions, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnAdmissions6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnTimetable, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbtnAdmissions7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnApplications, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnAdmissions8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbtnAdmissions9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtbtnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtbtnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtbtnAdmissions11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtbtnAdmissions2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtbtnCampuses, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbtnApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnApplicationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtnApplicationsActionPerformed

    private void jtbtnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnSettingsActionPerformed
        // TODO add your handling code here:
        new Settings().setVisible(true);
    }//GEN-LAST:event_jtbtnSettingsActionPerformed

    private void jtbtnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtnAttendanceActionPerformed

    private void jtbtnEnrolmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnEnrolmentsActionPerformed
        // TODO add your handling code here:
        new GradesForm().setVisible(true);
    }//GEN-LAST:event_jtbtnEnrolmentsActionPerformed

    private void jtbtnAdmissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAdmissionsActionPerformed
        // TODO add your handling code here:
        new Admission().setVisible(true);
    }//GEN-LAST:event_jtbtnAdmissionsActionPerformed

    private void jtbtnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAccountsActionPerformed
        // TODO add your handling code here:
        new Accounts().setVisible(true);
    }//GEN-LAST:event_jtbtnAccountsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Functions.setFormTheme();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFinance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jtbtnAccounts;
    private javax.swing.JToggleButton jtbtnAdmissions;
    private javax.swing.JToggleButton jtbtnAdmissions11;
    private javax.swing.JToggleButton jtbtnAdmissions2;
    private javax.swing.JToggleButton jtbtnAdmissions6;
    private javax.swing.JToggleButton jtbtnAdmissions7;
    private javax.swing.JToggleButton jtbtnAdmissions8;
    private javax.swing.JToggleButton jtbtnAdmissions9;
    private javax.swing.JToggleButton jtbtnApplications;
    private javax.swing.JToggleButton jtbtnAttendance;
    private javax.swing.JToggleButton jtbtnCampuses;
    private javax.swing.JToggleButton jtbtnEnrolments;
    private javax.swing.JToggleButton jtbtnSettings;
    private javax.swing.JToggleButton jtbtnStaff;
    private javax.swing.JToggleButton jtbtnTimetable;
    private javax.swing.JToggleButton jtbtnUsers;
    // End of variables declaration//GEN-END:variables
}
