/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nanoware.view;

import com.nanoware.bll.Functions;
import com.nanoware.bll.impl.StudentBoImpl;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.lang.Math.*;
import java.text.DecimalFormat;

/**
 *
 * @author Mothusi Molorane
 */
public class StudentModuleGrades extends javax.swing.JFrame {
    
    private final StudentBoImpl studentBoImpl = new StudentBoImpl();
    private DefaultTableModel tblModelStudentModuleGrades;
    private List<HashMap<String, Object>> grades;
    private double continuousAssessment;
    
    /**
     * Creates new form StudentModuleAssessment
     * @param personId
     * @param termId
     * @param moduleCode
     */
    public StudentModuleGrades(int personId, int termId, String moduleCode) {
        super(personId+" - Student Continuous Assessment");
        initComponents();
        Functions.setAppIcon(StudentModuleGrades.this);
        grades = studentBoImpl.StudentModuleGrades(personId, termId, moduleCode);
        tblModelStudentModuleGrades = (DefaultTableModel)tblModuleGrades.getModel();
        continuousAssessment = 0;
        displayGrades();
        setLocationRelativeTo(this);
    }
    
    public final void displayGrades(){
        tblModelStudentModuleGrades.setRowCount(0);
        grades.forEach((HashMap<String, Object> row) -> {
            continuousAssessment += Float.parseFloat(row.get("weighted").toString());
            tblModelStudentModuleGrades.addRow(new Object[]{
                row.get("gradecategory"),
                row.get("mark"),
                row.get("weight"),
                row.get("weighted")
             });
        });
        lblConsinuousAssessment.setText(Functions.toTwoDecimal(continuousAssessment)+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        tblModuleGrades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblConsinuousAssessment = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnStudentAssessment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane5.setBorder(null);

        tblModuleGrades.setAutoCreateRowSorter(true);
        tblModuleGrades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblModuleGrades.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tblModuleGrades.setForeground(new java.awt.Color(102, 102, 102));
        tblModuleGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Marks", "Weight", "Weighted"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblModuleGrades.setGridColor(new java.awt.Color(204, 204, 204));
        tblModuleGrades.setIntercellSpacing(new java.awt.Dimension(10, 10));
        tblModuleGrades.setRowHeight(40);
        jScrollPane5.setViewportView(tblModuleGrades);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CONTINUOUS ASSESSMENT:");

        lblConsinuousAssessment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblConsinuousAssessment.setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(Functions.pnlBackgroundTop());
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("If one of the grade categories is missing, yet it was uploaded, it's because the corresponding");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("grade weight is missing. The administrator or user in charge should upload the grade weight.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnStudentAssessment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnStudentAssessment.setForeground(new java.awt.Color(51, 51, 51));
        btnStudentAssessment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        btnStudentAssessment.setToolTipText("Print student assessment");
        btnStudentAssessment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAssessmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStudentAssessment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConsinuousAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsinuousAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnStudentAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentAssessmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAssessmentActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnStudentAssessmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Functions.setFormTheme();
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentModuleGrades(0,0,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentAssessment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConsinuousAssessment;
    private javax.swing.JTable tblModuleGrades;
    // End of variables declaration//GEN-END:variables
}
