/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.molorane.college.view.principal;

import com.molorane.college.view.admin.*;
import com.molorane.college.view.lecture.GradesFrm;
import com.molorane.college.custom.Functions;
import com.molorane.college.custom.LoginSession;
import com.molorane.college.view.Controls.AdmissionFrm;
import com.molorane.college.view.Controls.EnrolmentFrm;

/**
 *
 * @author Mothusi Molorane
 */
public class PrincipalMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public PrincipalMenu() {
        super("Dashboard - "+Functions.appName());
        initComponents();
        LoginSession.setDashboard(this);
        Functions.initForm(PrincipalMenu.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnTerm = new javax.swing.JToggleButton();
        jtbtnApplications = new javax.swing.JToggleButton();
        btnSettings = new javax.swing.JToggleButton();
        jtbtnUsers = new javax.swing.JToggleButton();
        jtbtnAttendance = new javax.swing.JToggleButton();
        jtbtnAdmissions2 = new javax.swing.JToggleButton();
        jtbtnStaff = new javax.swing.JToggleButton();
        btnEnrolment = new javax.swing.JToggleButton();
        btnAdmission = new javax.swing.JToggleButton();
        btnAccount = new javax.swing.JToggleButton();
        btnGrades = new javax.swing.JToggleButton();
        jtbtnEntryForm = new javax.swing.JToggleButton();
        jtbtnAdmissions8 = new javax.swing.JToggleButton();
        jtbtnAssessments = new javax.swing.JToggleButton();
        jtbtnCampuses = new javax.swing.JToggleButton();
        jtbtnAdmissions11 = new javax.swing.JToggleButton();
        jbtnTimeTable = new javax.swing.JButton();
        jbtnMatric = new javax.swing.JButton();
        footer = new com.molorane.college.view.Controls.CopyrightPnl();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(Functions.pnlBackgroundTop());
        jPanel4.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("PRINCIPAL");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(Functions.dashboardTitle());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        btnTerm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTerm.setForeground(new java.awt.Color(102, 102, 102));
        btnTerm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/schedule.png"))); // NOI18N
        btnTerm.setText("Terms");
        btnTerm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTerm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTermActionPerformed(evt);
            }
        });

        jtbtnApplications.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnApplications.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnApplications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/application.png"))); // NOI18N
        jtbtnApplications.setText("Applications");
        jtbtnApplications.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnApplications.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnApplicationsActionPerformed(evt);
            }
        });

        btnSettings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSettings.setForeground(new java.awt.Color(102, 102, 102));
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/settings1.png"))); // NOI18N
        btnSettings.setText("Settings");
        btnSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        jtbtnUsers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnUsers.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/account.png"))); // NOI18N
        jtbtnUsers.setText("Users");
        jtbtnUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnUsersActionPerformed(evt);
            }
        });

        jtbtnAttendance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAttendance.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/attendance.png"))); // NOI18N
        jtbtnAttendance.setText("Attendance");
        jtbtnAttendance.setDoubleBuffered(true);
        jtbtnAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAttendance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAttendanceActionPerformed(evt);
            }
        });

        jtbtnAdmissions2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions2.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/bank.png"))); // NOI18N
        jtbtnAdmissions2.setText("Sponsors");
        jtbtnAdmissions2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jtbtnStaff.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnStaff.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/service.png"))); // NOI18N
        jtbtnStaff.setText("Staff");
        jtbtnStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnStaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnStaffActionPerformed(evt);
            }
        });

        btnEnrolment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEnrolment.setForeground(new java.awt.Color(102, 102, 102));
        btnEnrolment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/clipboard.png"))); // NOI18N
        btnEnrolment.setText("Enrolments");
        btnEnrolment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnrolment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnrolment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrolmentActionPerformed(evt);
            }
        });

        btnAdmission.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdmission.setForeground(new java.awt.Color(102, 102, 102));
        btnAdmission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/icon2.png"))); // NOI18N
        btnAdmission.setText("Admissions");
        btnAdmission.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmission.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmissionActionPerformed(evt);
            }
        });

        btnAccount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(102, 102, 102));
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/shopping-cart.png"))); // NOI18N
        btnAccount.setText("Accounts");
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        btnGrades.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnGrades.setForeground(new java.awt.Color(102, 102, 102));
        btnGrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/speaker.png"))); // NOI18N
        btnGrades.setText("Grades");
        btnGrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradesActionPerformed(evt);
            }
        });

        jtbtnEntryForm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnEntryForm.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnEntryForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/test.png"))); // NOI18N
        jtbtnEntryForm.setText("Entry Forms");
        jtbtnEntryForm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnEntryForm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnEntryForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnEntryFormActionPerformed(evt);
            }
        });

        jtbtnAdmissions8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions8.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/pass1.png"))); // NOI18N
        jtbtnAdmissions8.setText("Exams");
        jtbtnAdmissions8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnAdmissions8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAdmissions8ActionPerformed(evt);
            }
        });

        jtbtnAssessments.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAssessments.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAssessments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/law1.png"))); // NOI18N
        jtbtnAssessments.setText("Assessments");
        jtbtnAssessments.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAssessments.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnAssessments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAssessmentsActionPerformed(evt);
            }
        });

        jtbtnCampuses.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnCampuses.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnCampuses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/campus.png"))); // NOI18N
        jtbtnCampuses.setText("Campuses");
        jtbtnCampuses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnCampuses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnCampuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnCampusesActionPerformed(evt);
            }
        });

        jtbtnAdmissions11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtbtnAdmissions11.setForeground(new java.awt.Color(102, 102, 102));
        jtbtnAdmissions11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/analytics4.png"))); // NOI18N
        jtbtnAdmissions11.setText("Results");
        jtbtnAdmissions11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbtnAdmissions11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbtnAdmissions11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAdmissions11ActionPerformed(evt);
            }
        });

        jbtnTimeTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnTimeTable.setForeground(new java.awt.Color(102, 102, 102));
        jbtnTimeTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/clock.png"))); // NOI18N
        jbtnTimeTable.setText("Time Table");
        jbtnTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnTimeTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnTimeTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimeTableActionPerformed(evt);
            }
        });

        jbtnMatric.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnMatric.setForeground(new java.awt.Color(102, 102, 102));
        jbtnMatric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/molorane/college/images/dashboard/staff.png"))); // NOI18N
        jbtnMatric.setText("Students");
        jbtnMatric.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMatric.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnMatric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMatricActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnMatric, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtbtnStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnrolment, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtbtnAdmissions8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdmission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtbtnAssessments)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtbtnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtbtnEntryForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbtnCampuses, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtbtnAdmissions11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbtnAdmissions2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbtnApplications, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbtnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAccount, btnAdmission, btnEnrolment, btnGrades, btnSettings, btnTerm, jbtnMatric, jbtnTimeTable, jtbtnAdmissions11, jtbtnAdmissions2, jtbtnAdmissions8, jtbtnApplications, jtbtnAssessments, jtbtnAttendance, jtbtnCampuses, jtbtnEntryForm, jtbtnStaff, jtbtnUsers});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGrades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdmission, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnrolment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTerm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnEntryForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbtnStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jtbtnAdmissions8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnAssessments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnCampuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtbtnAdmissions11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnTimeTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnMatric, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jtbtnAdmissions2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnApplications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbtnAttendance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAccount, btnAdmission, btnEnrolment, btnGrades, btnSettings, btnTerm, jbtnMatric, jbtnTimeTable, jtbtnAdmissions11, jtbtnAdmissions2, jtbtnAdmissions8, jtbtnApplications, jtbtnAssessments, jtbtnAttendance, jtbtnCampuses, jtbtnEntryForm, jtbtnStaff, jtbtnUsers});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbtnApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnApplicationsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtbtnApplicationsActionPerformed

    private void jtbtnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAttendanceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtbtnAttendanceActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
        new Settings().setVisible(true);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnEnrolmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrolmentActionPerformed
        // TODO add your handling code here:
        new EnrolmentFrm().setVisible(true);
    }//GEN-LAST:event_btnEnrolmentActionPerformed

    private void btnAdmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmissionActionPerformed
        // TODO add your handling code here:
        new AdmissionFrm().setVisible(true);
    }//GEN-LAST:event_btnAdmissionActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradesActionPerformed
        // TODO add your handling code here:
        new GradesFrm().setVisible(true);
    }//GEN-LAST:event_btnGradesActionPerformed

    private void btnTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTermActionPerformed
        // TODO add your handling code here:
        new TermFrm().setVisible(true);
    }//GEN-LAST:event_btnTermActionPerformed

    private void jbtnMatricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMatricActionPerformed
        // TODO add your handling code here:
        new UploadStudents().setVisible(true);
    }//GEN-LAST:event_jbtnMatricActionPerformed

    private void jtbtnAssessmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAssessmentsActionPerformed
        // TODO add your handling code here:
        new AssessmentFrm().setVisible(true);
    }//GEN-LAST:event_jtbtnAssessmentsActionPerformed

    private void jtbtnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnStaffActionPerformed
        // TODO add your handling code here:
        new StaffFrm().setVisible(true);
    }//GEN-LAST:event_jtbtnStaffActionPerformed

    private void jtbtnEntryFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnEntryFormActionPerformed
        // TODO add your handling code here:
        new EntryFrm().setVisible(true);
    }//GEN-LAST:event_jtbtnEntryFormActionPerformed

    private void jtbtnAdmissions8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAdmissions8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtnAdmissions8ActionPerformed

    private void jtbtnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtnUsersActionPerformed

    private void jtbtnCampusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnCampusesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtnCampusesActionPerformed

    private void jbtnTimeTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimeTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTimeTableActionPerformed

    private void jtbtnAdmissions11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAdmissions11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtnAdmissions11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Functions.setFormTheme();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAccount;
    private javax.swing.JToggleButton btnAdmission;
    private javax.swing.JToggleButton btnEnrolment;
    private javax.swing.JToggleButton btnGrades;
    private javax.swing.JToggleButton btnSettings;
    private javax.swing.JToggleButton btnTerm;
    private com.molorane.college.view.Controls.CopyrightPnl footer;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnMatric;
    private javax.swing.JButton jbtnTimeTable;
    private javax.swing.JToggleButton jtbtnAdmissions11;
    private javax.swing.JToggleButton jtbtnAdmissions2;
    private javax.swing.JToggleButton jtbtnAdmissions8;
    private javax.swing.JToggleButton jtbtnApplications;
    private javax.swing.JToggleButton jtbtnAssessments;
    private javax.swing.JToggleButton jtbtnAttendance;
    private javax.swing.JToggleButton jtbtnCampuses;
    private javax.swing.JToggleButton jtbtnEntryForm;
    private javax.swing.JToggleButton jtbtnStaff;
    private javax.swing.JToggleButton jtbtnUsers;
    // End of variables declaration//GEN-END:variables
}
